project:
  type: website
  output-dir: docs
  

website:
  title: "SWH Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: FYP Project
      - href: new1.qmd
        text: Data Visualisation
      - href: new2.qmd
        text: Reflection
        
format:
  html:
    theme:
      - darkly
      - brand
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: left



